
server:
    port: 8081

spring:
    cloud:
        server:
            git:
                uri: https://github.com/victorgomez09/workcode
                search-paths: config-data
    application:
        name: config-service
