
server:
    port: 8081

spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/victorgomez09/workcode
                    search-paths: backend/config-data
                    default-label: main
            # profile: main
    application:
        name: config-service
