server:
  port: 8001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workcode_users
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
